package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 21 12:12:31 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExEmpAttachment_EOViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ExEmpAttachment_EOViewImpl() {
    }
}

